



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
   package characterarena;

/**
 *
 * @author glady
 */
public class HeroArenaApp extends javax.swing.JFrame {
    private GameManager manager = new GameManager();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HeroArenaApp.class.getName());

   
    public HeroArenaApp() {
        initComponents();
    }

   

       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Hero Quest Arena");

        jButton2.setBackground(new java.awt.Color(255, 153, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Create Hero");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Simulate Battle");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Display Heroes");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(255, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Upgrade Stats");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String name = javax.swing.JOptionPane.showInputDialog (this, "Enter hero name:");
if (name == null || name.isEmpty()) return;


String[] types = {"Warrior", "Mage", "Archer"};
String type = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Choose hero class:",
        "Hero Class",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        types,
        types[0]);

if (type == null) return;

Hero hero;
String hpInput = javax.swing.JOptionPane.showInputDialog(this, "Enter HP:");
 if (hpInput == null) return;

String attackInput = javax.swing.JOptionPane.showInputDialog(this, "Enter Attack:");
if (attackInput == null) return;

String defenceInput = javax.swing.JOptionPane.showInputDialog(this, "Enter Defence:");
if (defenceInput == null) return;

int hp;
int attack;
int defence;

try {
    hp = Integer.parseInt(hpInput);
    attack = Integer.parseInt(attackInput);
  defence = Integer.parseInt(defenceInput);
}
 catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers!");
    return;
}




if (type.equals("Warrior")) {
    hero = new Warrior(name, hp, attack, defence);
} 
else if (type.equals("Mage")) {
    hero = new Mage(name, hp, attack, defence);
} 
else {
    hero = new Archer(name, hp, attack, defence);
}






manager.addHero(hero);
javax.swing.JOptionPane.showMessageDialog(this, "Hero created!");
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     if (manager.getHeroes().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "No heroes created yet.");
    return;
}

String output = "";
for (Hero h : manager.getHeroes()) {
    output += h.getName()
            + " | HP: " + h.getHp()
            + " | ATK: " + h.getAttack()
            + " | DEF: " + h.getDefence()
            + "\n";
}

javax.swing.JOptionPane.showMessageDialog(this, output);
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     if (manager.getHeroes().isEmpty()) return;

String[] names = new String[manager.getHeroes().size()];
for (int i = 0; i < manager.getHeroes().size(); i++) {
    names[i] = manager.getHeroes().get(i).getName();
}

String selected = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Select hero to upgrade:",
        "Upgrade Hero",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        names,
        names[0]);

if (selected == null) return;

for (Hero h : manager.getHeroes()) {
    if (h.getName().equals(selected)) {
        if (h.upgrade()) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Hero upgraded successfully!");
    
} else {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Not enough experience! Win battles first.");
}

        break;
    }
}
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      System.exit(0);
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  if (manager.getHeroes().size() < 2) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "You need at least 2 heroes to battle.");
    return;   
}

String[] names = new String[manager.getHeroes().size()];
for (int i = 0; i < manager.getHeroes().size(); i++) {
    names[i] = manager.getHeroes().get(i).getName();
}

String hero1Name = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Select first hero:",
        "Battle",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        names,
        names[0]);

if (hero1Name == null) return;

String hero2Name = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Select second hero:",
        "Battle",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        names,
        names[0]);

if (hero2Name == null || hero1Name.equals(hero2Name)) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Choose two different heroes.");
    return;
}

Hero hero1 = null;
Hero hero2 = null;

for (Hero h : manager.getHeroes()) {
    if (h.getName().equals(hero1Name)) hero1 = h;
    if (h.getName().equals(hero2Name)) hero2 = h;
}

int score1 = hero1.getAttack() + hero1.getDefence() + hero1.getHp();
int score2 = hero2.getAttack() + hero2.getDefence() + hero2.getHp();

String result;
if (score1 > score2) {
    result = hero1.getName() + " WINS! 🏆";
    hero1.addExperience(10);
} else if (score2 > score1) {
    result = hero2.getName() + " WINS! 🏆";
    hero2.addExperience(10);
} else {
    result = "It's a DRAW 🤝";
}


javax.swing.JOptionPane.showMessageDialog(this,
        hero1.getName() + " vs " + hero2.getName()
        + "\n\n" + result);
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
    

    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

}